### ISSUE TITLE
bouwen

### ISSUE THREAD

**Issue by casdr** [Hostio/WHMCS#1]
duurt lang @janyksteenbeek

**Comment by janyksteenbeek** [comment]
Bedankt voor je bericht, @casdr. Ik begrijp je frustratie. Echter focussen we bij Hostio momenteel op andere elementen van ons klantenpaneel, en hebben we de WHMCS module even uitgesteld. Uiteraard houden we je op de hoogte van alle ontwikkelingen via @HostioSolutions op Twitter.
